name: Deploy MLFlow App

on:
  push:
    branches:
      - enh/5/*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Pull Docker image
        run: |
          docker pull narendrakumar291/ml_flow:v3

      - name: Run Docker container
        run: |
          docker run -d -p 5000:5000 narendrakumar291/ml_flow:v3
